version: '3'
services:
  web:
    image: dignz/gd-fix:latest
    working_dir: /var/www
    volumes:
      - .:/var/www/html
    environment:
      VIRTUAL_HOST: joydrone.littlemonkey.info
      LETSENCRYPT_HOST: joydrone.littlemonkey.info
      LETSENCRYPT_EMAIL: joy@littlemonkey.co.nz
    expose:
      - "80"
      - "443"
    networks:
      - outside
      - db-net
  database:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - db-net
volumes:
  db-data:

networks:
  outside:
    external:
      name: nginx-proxy
  db-net:
